/*
 * Icon key -> FontAwesome glyph, for controls configured in Headwaters.
 *
 * GENERATED by GUI/tmp/light_icons.py from Headwaters'
 * containers/frontend/public/js/components/fireside-icons.js -- do not edit
 * by hand. Regenerate when that file changes.
 *
 * A control arrives as { id, name, icon } where `icon` is a key, so the
 * dial has to resolve it the same way the PWA does or the user picks one
 * icon and sees another. Legacy keys are folded in for the same reason
 * LEGACY_KEY_MAP exists upstream: a value stored under an old name must
 * still render.
 *
 * Every codepoint here is inside the project's FontAwesome subset; a
 * codepoint outside it draws an empty box and warns about nothing.
 * gen_eez_project.py enforces that.
 */
#pragma once

#include <string.h>

#define UI_LIGHT_ICON_FALLBACK "\xEF\x83\xAB"   /* 0xF0EB lightbulb */

typedef struct {
    const char *key;
    const char *glyph;
} ui_light_icon_t;

static const ui_light_icon_t UI_LIGHT_ICONS[] = {
    { "lightbulb", "\xEF\x83\xAB" },   /* 0xF0EB */
    { "sun", "\xEF\x86\x85" },   /* 0xF185 */
    { "moon", "\xEF\x86\x86" },   /* 0xF186 */
    { "cloud", "\xEF\x83\x82" },   /* 0xF0C2 */
    { "umbrella", "\xEF\x83\xA9" },   /* 0xF0E9 */
    { "snowflake", "\xEF\x8B\x9C" },   /* 0xF2DC */
    { "fire", "\xEF\x81\xAD" },   /* 0xF06D */
    { "fire-flame-curved", "\xEF\x9F\xA4" },   /* 0xF7E4 */
    { "bolt", "\xEF\x83\xA7" },   /* 0xF0E7 */
    { "plug", "\xEF\x87\xA6" },   /* 0xF1E6 */
    { "battery-full", "\xEF\x89\x80" },   /* 0xF240 */
    { "charging-station", "\xEF\x97\xA7" },   /* 0xF5E7 */
    { "fan", "\xEF\xA1\xA3" },   /* 0xF863 */
    { "paint-roller", "\xEF\x96\xAA" },   /* 0xF5AA */
    { "droplet", "\xEF\x81\x83" },   /* 0xF043 */
    { "faucet", "\xEE\x80\x85" },   /* 0xE005 */
    { "water", "\xEF\x9D\xB3" },   /* 0xF773 */
    { "bath", "\xEF\x8B\x8D" },   /* 0xF2CD */
    { "utensils", "\xEF\x8B\xA7" },   /* 0xF2E7 */
    { "mug-hot", "\xEF\x9E\xB6" },   /* 0xF7B6 */
    { "mug-saucer", "\xEF\x83\xB4" },   /* 0xF0F4 */
    { "house", "\xEF\x80\x95" },   /* 0xF015 */
    { "building", "\xEF\x86\xAD" },   /* 0xF1AD */
    { "door-closed", "\xEF\x94\xAA" },   /* 0xF52A */
    { "warehouse", "\xEF\x92\x94" },   /* 0xF494 */
    { "bed", "\xEF\x88\xB6" },   /* 0xF236 */
    { "shop", "\xEF\x95\x8F" },   /* 0xF54F */
    { "shirt", "\xEF\x95\x93" },   /* 0xF553 */
    { "tree", "\xEF\x86\xBB" },   /* 0xF1BB */
    { "leaf", "\xEF\x81\xAC" },   /* 0xF06C */
    { "mountain", "\xEF\x9B\xBC" },   /* 0xF6FC */
    { "globe", "\xEF\x82\xAC" },   /* 0xF0AC */
    { "caravan", "\xEF\xA3\xBF" },   /* 0xF8FF */
    { "car", "\xEF\x86\xB9" },   /* 0xF1B9 */
    { "truck", "\xEF\x83\x91" },   /* 0xF0D1 */
    { "bicycle", "\xEF\x88\x86" },   /* 0xF206 */
    { "plane", "\xEF\x81\xB2" },   /* 0xF072 */
    { "rocket", "\xEF\x84\xB5" },   /* 0xF135 */
    { "location-dot", "\xEF\x8F\x85" },   /* 0xF3C5 */
    { "location-pin", "\xEF\x81\x81" },   /* 0xF041 */
    { "layer-group", "\xEF\x97\xBD" },   /* 0xF5FD */
    { "camera-retro", "\xEF\x82\x83" },   /* 0xF083 */
    { "film", "\xEF\x80\x88" },   /* 0xF008 */
    { "music", "\xEF\x80\x81" },   /* 0xF001 */
    { "headphones", "\xEF\x80\xA5" },   /* 0xF025 */
    { "play", "\xEF\x81\x8B" },   /* 0xF04B */
    { "backward", "\xEF\x81\x8A" },   /* 0xF04A */
    { "stop", "\xEF\x81\x8D" },   /* 0xF04D */
    { "gamepad", "\xEF\x84\x9B" },   /* 0xF11B */
    { "phone", "\xEF\x82\x95" },   /* 0xF095 */
    { "comment", "\xEF\x81\xB5" },   /* 0xF075 */
    { "wifi", "\xEF\x87\xAB" },   /* 0xF1EB */
    { "satellite-dish", "\xEF\x9F\x80" },   /* 0xF7C0 */
    { "users", "\xEF\x83\x80" },   /* 0xF0C0 */
    { "user", "\xEF\x80\x87" },   /* 0xF007 */
    { "person", "\xEF\x86\x83" },   /* 0xF183 */
    { "user-secret", "\xEF\x88\x9B" },   /* 0xF21B */
    { "bell", "\xEF\x83\xB3" },   /* 0xF0F3 */
    { "stethoscope", "\xEF\x83\xB1" },   /* 0xF0F1 */
    { "eye", "\xEF\x81\xAE" },   /* 0xF06E */
    { "shield", "\xEF\x84\xB2" },   /* 0xF132 */
    { "dumpster-fire", "\xEF\x9E\x94" },   /* 0xF794 */
    { "lock", "\xEF\x80\xA3" },   /* 0xF023 */
    { "key", "\xEF\x82\x84" },   /* 0xF084 */
    { "right-to-bracket", "\xEF\x8B\xB6" },   /* 0xF2F6 */
    { "clock", "\xEF\x80\x97" },   /* 0xF017 */
    { "calendar", "\xEF\x84\xB3" },   /* 0xF133 */
    { "calendar-days", "\xEF\x81\xB3" },   /* 0xF073 */
    { "heart", "\xEF\x80\x84" },   /* 0xF004 */
    { "star", "\xEF\x80\x85" },   /* 0xF005 */
    { "thumbs-up", "\xEF\x85\xA4" },   /* 0xF164 */
    { "gift", "\xEF\x81\xAB" },   /* 0xF06B */
    { "credit-card", "\xEF\x82\x9D" },   /* 0xF09D */
    { "briefcase", "\xEF\x82\xB1" },   /* 0xF0B1 */
    { "paperclip", "\xEF\x83\x86" },   /* 0xF0C6 */
    { "book", "\xEF\x80\xAD" },   /* 0xF02D */
    { "bag-shopping", "\xEF\x8A\x90" },   /* 0xF290 */
    { "gear", "\xEF\x80\x93" },   /* 0xF013 */
    { "sliders", "\xEF\x87\x9E" },   /* 0xF1DE */
    { "magnifying-glass", "\xEF\x80\x82" },   /* 0xF002 */
    { "circle-info", "\xEF\x81\x9A" },   /* 0xF05A */
    { "cloud-arrow-up", "\xEF\x83\xAE" },   /* 0xF0EE */
    { "expand", "\xEF\x81\xA5" },   /* 0xF065 */
    { "trash", "\xEF\x87\xB8" },   /* 0xF1F8 */
    { "antenna", "\xEF\x9F\x80" },   /* 0xF7C0 */
    { "awning", "\xEF\xA3\xBF" },   /* 0xF8FF */
    { "ceiling-light", "\xEF\x83\xAB" },   /* 0xF0EB */
    { "exterior-light", "\xEF\x83\xAB" },   /* 0xF0EB */
    { "fridge", "\xEF\x8B\x9C" },   /* 0xF2DC */
    { "generic", "\xEF\x80\x93" },   /* 0xF013 */
    { "heater", "\xEF\x81\xAD" },   /* 0xF06D */
    { "power-outlet", "\xEF\x87\xA6" },   /* 0xF1E6 */
    { "speaker", "\xEF\x80\x81" },   /* 0xF001 */
    { "step", "\xEF\x80\x95" },   /* 0xF015 */
    { "strip-light", "\xEF\x83\xAB" },   /* 0xF0EB */
    { "water-pump", "\xEF\x9D\xB3" },   /* 0xF773 */
};

/** Resolve an icon key to a glyph, falling back to the bulb like the PWA. */
static inline const char *ui_light_icon(const char *key)
{
    if (!key || !key[0]) {
        return UI_LIGHT_ICON_FALLBACK;
    }
    for (size_t i = 0; i < sizeof(UI_LIGHT_ICONS) / sizeof(*UI_LIGHT_ICONS); i++) {
        if (strcmp(UI_LIGHT_ICONS[i].key, key) == 0) {
            return UI_LIGHT_ICONS[i].glyph;
        }
    }
    return UI_LIGHT_ICON_FALLBACK;
}
