idf_component_register(
    SRCS
        "src/capstan_board.c"
        "src/board_display.c"
        "src/board_touch.c"
        "src/board_encoder.c"
        "src/panel_jd9855.c"
        "src/capstan_touch_cal.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "src"
    REQUIRES
        capstan_config
        esp_lcd
        espressif__esp_lvgl_port
        lvgl__lvgl
        driver
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_pcnt
        esp_driver_i2c
        esp_timer
    PRIV_REQUIRES
        esp_psram
)
